create table app_users (
    id bigint generated by default as identity,
    username varchar(50) not null,
    password_hash varchar(255) not null,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint pk_app_users primary key (id),
    constraint uk_app_users_username unique (username)
);

create table quotes (
    id bigint generated by default as identity,
    text varchar(1000) not null,
    author varchar(120) not null,
    source varchar(160),
    constraint pk_quotes primary key (id)
);

create table stories (
    id bigint generated by default as identity,
    title varchar(160) not null,
    content varchar(8000) not null,
    created_at timestamp(6) with time zone not null default current_timestamp,
    updated_at timestamp(6) with time zone not null default current_timestamp,
    author_id bigint not null,
    quote_id bigint not null,
    constraint pk_stories primary key (id),
    constraint fk_stories_author foreign key (author_id) references app_users (id),
    constraint fk_stories_quote foreign key (quote_id) references quotes (id)
);

create table story_event_logs (
    id bigint generated by default as identity,
    story_id bigint not null,
    event_type varchar(50) not null,
    username varchar(50) not null,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint pk_story_event_logs primary key (id)
);

create index idx_stories_created_at on stories (created_at desc);
create index idx_stories_author_id on stories (author_id);
create index idx_story_event_logs_created_at on story_event_logs (created_at desc);

insert into quotes (text, author, source) values
    ('A blank page is a door waiting for a brave hand.', 'Storyline', 'Seed quote'),
    ('Even a small scene can carry a whole world.', 'Storyline', 'Seed quote'),
    ('Start with one true detail and let the story find its weather.', 'Storyline', 'Seed quote'),
    ('A character becomes real when they want something enough to move.', 'Storyline', 'Seed quote'),
    ('The best endings echo the first question in a new voice.', 'Storyline', 'Seed quote');
